import type { Language } from "./types";
const en = {
  sourceLibrary: "SOURCE LIBRARY", documentType: "Product brochure · English / 中文",
  subtitle: "Your guide to the fine print", language: "Interface language", newChat: "New conversation",
  eyebrow: "DOCUMENT-GROUNDED INSURANCE TUTOR", title: "Understand your cover.",
  introduction: "Ask about FLEXI-ULife Prime Saver. Explore benefits, conditions and charges, with references to the original brochure.",
  examples: ["Is the 4% interest rate guaranteed?", "What happens if I stop paying premiums?", "How does the cooling-off period work?"],
  suggestions: "A few places to start", question: "Your question", placeholder: "Ask about benefits, premiums or policy conditions…",
  send: "Ask InsureTutor", you: "You", assistant: "InsureTutor",
  stop: "Stop", citationHint: "Click a numbered reference to open its PDF page.",
  phases: { classifying: "Understanding your question…", retrieving: "Finding supporting passages…", generating: "Writing an answer with sources…", checking: "Checking the answer…" },
  page: "PDF page", open: "Open source PDF", reference: "Reference", ready: "Document ready", checking: "Checking document…",
  setup: "Setup needs attention", retry: "Check again", connection: "Unable to connect. Make sure the backend is running, then try again.",
  error: "The question could not be answered. Please try again.", extracted: "Source text mode",
  about: "One document. Clear references.", aboutText: "Each answer links back to its evidence. Page numbers refer to the PDF file, starting at page 1.",
  note: "For understanding the brochure. Full policy terms govern the cover; this tutor does not provide personal insurance advice.",
  local: "PDF, index and conversation history are stored locally. Relevant passages and questions are sent to the configured model API.",
  statuses: { answered: "Source-supported", insufficient_evidence: "More evidence needed", out_of_scope: "Outside scope", blocked: "Request declined", conflict: "Source discrepancy", clarification_required: "Please clarify" },
};
const hans: typeof en = {
  sourceLibrary: "来源文档", documentType: "产品宣传册 · English / 中文",
  subtitle: "读懂保险条款", language: "界面语言", newChat: "新对话",
  eyebrow: "基于文档的保险问答", title: "了解保障，读懂细节。",
  introduction: "询问首选灵活万用寿险计划的保障、条件和费用，查看回答对应的宣传册原文。",
  examples: ["4%的利率是保证的吗？", "停止缴付保费会怎样？", "冷静期如何计算？"],
  suggestions: "可以从这些问题开始", question: "你的问题", placeholder: "询问保障、保费或保单条件……",
  send: "发送问题", you: "你", assistant: "InsureTutor",
  stop: "停止", citationHint: "点击回答中的引用编号，查看对应 PDF 页。",
  phases: { classifying: "正在理解问题……", retrieving: "正在查找原文依据……", generating: "正在生成带引用的回答……", checking: "正在检查回答……" },
  page: "PDF 页码", open: "打开原始 PDF", reference: "引用", ready: "文档已就绪", checking: "正在检查文档……",
  setup: "需要完成配置", retry: "重新检查", connection: "无法连接，请确认后端已经启动后重试。",
  error: "暂时无法回答，请重试。", extracted: "原文检索模式",
  about: "一份文档，出处清晰。", aboutText: "每条回答均可查看对应原文。页码从 PDF 文件的第 1 页开始计算。",
  note: "用于理解宣传册，完整保障以保单条款为准。本工具不提供个人投保建议。",
  local: "PDF、索引和对话记录保存在本地；相关段落和问题会发送至配置的模型 API。",
  statuses: { answered: "附有原文依据", insufficient_evidence: "证据不足", out_of_scope: "超出范围", blocked: "请求已拒绝", conflict: "来源存在差异", clarification_required: "请补充说明" },
};
const hant: typeof en = {
  ...hans, sourceLibrary: "來源文檔", documentType: "產品宣傳冊 · English / 中文", subtitle: "讀懂保險條款", language: "介面語言", newChat: "新對話",
  eyebrow: "基於文檔的保險問答", title: "了解保障，讀懂細節。",
  introduction: "詢問首選靈活萬用壽險計劃的保障、條件和費用，查看回答對應的宣傳冊原文。",
  examples: ["4%的利率是保證的嗎？", "停止繳付保費會怎樣？", "冷靜期如何計算？"],
  suggestions: "可以從這些問題開始", question: "你的問題", placeholder: "詢問保障、保費或保單條件……",
  send: "發送問題", you: "你",
  stop: "停止", citationHint: "點擊回答中的引用編號，查看對應 PDF 頁。",
  phases: { classifying: "正在理解問題……", retrieving: "正在查找原文依據……", generating: "正在生成帶引用的回答……", checking: "正在檢查回答……" },
  page: "PDF 頁碼", open: "開啟原始 PDF", reference: "引用", ready: "文檔已就緒", checking: "正在檢查文檔……",
  setup: "需要完成配置", retry: "重新檢查", connection: "無法連接，請確認後端已經啟動後重試。",
  error: "暫時無法回答，請重試。", extracted: "原文檢索模式",
  about: "一份文檔，出處清晰。", aboutText: "每條回答均可查看對應原文。頁碼從 PDF 檔案的第 1 頁開始計算。",
  note: "用於理解宣傳冊，完整保障以保單條款為準。本工具不提供個人投保建議。",
  local: "PDF、索引和對話記錄保存在本地；相關段落和問題會發送至配置的模型 API。",
  statuses: { answered: "附有原文依據", insufficient_evidence: "證據不足", out_of_scope: "超出範圍", blocked: "請求已拒絕", conflict: "來源存在差異", clarification_required: "請補充說明" },
};
export const copy = (language: Language) => ({ en, "zh-Hans": hans, "zh-Hant": hant })[language];
